basePath: /
definitions:
  model.UserRequest:
    properties:
      age:
        type: integer
      dob:
        type: string
      mobile:
        type: string
      name:
        type: string
      pan:
        type: string
    required:
    - age
    - dob
    - mobile
    - name
    - pan
    type: object
  model.UserResponse:
    properties:
      age:
        type: integer
      dob:
        type: string
      mobile:
        type: string
      name:
        type: string
      pan:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for user registration.
  title: Go Watchlist API
  version: "1.0"
paths:
  /register/add:
    post:
      consumes:
      - application/json
      description: Register a new user by providing name, PAN, mobile, age, and DOB
      parameters:
      - description: User registration input
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Register a new user
      tags:
      - User
swagger: "2.0"
